### ISSUE TITLE
World Map: Setting pool-sliders is tedious, for one change implies changes in neighbor pool as well

### ISSUE THREAD

**Issue by kats4** [carbonara-coinpensator/carbonara-frontend#37]
Setting the pool-sliders to a specific setting is tedious, because the change in one pool implies changes in the neighbour pool as well.

**Comment by OleGiebel** [comment]
Hey @kats4, I had a look into how the region slider works and what we can do about it as a first shot. 

From a technical perspective we could introduce a region slider component that is configurable (region and slider change handling). On the world map we would use one slider per region and after a slide action validate that all consumption add up to 100%. If they do not add up, we show an info message that they need to add up.

**Comment by kats4** [comment]
@OleGiebel  I like the validation and the info message. That is more transparent for the user.

**Comment by ikeedo** [comment]
We have now implemented new slider controls: there is one slider control for each country/region. So multiple slider thumbs do not get mixed up in one slider track anymore. 

The values still add up to 100% automatically. This might be a better solution compared to the above proposed solution, where the users have to add the values up by themselves in order to match 100%, since we want to keep the user experience as simple as possible. 

If there is still need for discussion, please feel free to open a new issue. The current slider solution might still not be the best one regarding user experience :-D
